"""Add os_vinculada_id to activities

Revision ID: a605d5c373df
Revises: 3c4d5e6f7a8b
Create Date: 2026-06-10 16:44:39.111006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a605d5c373df'
down_revision: Union[str, Sequence[str], None] = '3c4d5e6f7a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os_vinculada_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_activities_os_vinculada_id'), ['os_vinculada_id'], unique=False)
        batch_op.create_foreign_key('fk_activities_os_vinculada', 'activities', ['os_vinculada_id'], ['id'])


def downgrade() -> None:
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_os_vinculada', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activities_os_vinculada_id'))
        batch_op.drop_column('os_vinculada_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('perfil',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'visualizador'"))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transfers_to_company', type_='foreignkey')
        batch_op.drop_constraint('fk_transfers_printer', type_='foreignkey')
        batch_op.drop_constraint('fk_transfers_from_company', type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('observacao',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('responsavel_recebimento',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('responsavel_entrega',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('numero_os',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('printer_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_printers_company', type_='foreignkey')
        batch_op.alter_column('tecnico',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('mac_address',
               existing_type=sa.VARCHAR(length=17),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('ip_rede',
               existing_type=sa.VARCHAR(length=45),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('marca',
               existing_type=sa.VARCHAR(length=80),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.alter_column('modelo_compativel',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'cliente'"))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('uf',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attachments_uploader', type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('size_bytes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('original_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_alerts_printer', type_='foreignkey')
        batch_op.drop_constraint('fk_alerts_resolved_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alerts_part_id'))
        batch_op.create_index(batch_op.f('ix_alert_part_id'), ['part_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('resolvido',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_to_company', type_='foreignkey')
        batch_op.drop_constraint('fk_activities_technician', type_='foreignkey')
        batch_op.drop_constraint('fk_activities_from_company', type_='foreignkey')
        batch_op.drop_constraint('fk_activities_os_vinculada', type_='foreignkey')
        batch_op.drop_constraint('fk_activities_printer', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activities_os_vinculada_id'))
        batch_op.alter_column('custo_servico',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('numero_recibo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.drop_column('os_vinculada_id')

    # ### end Alembic commands ###
