from .dashboard_page import DashboardPage
from .printers_page import PrintersPage
from .os_page import OSPage
from .clients_page import ClientsPage
from .parts_page import PartsPage
from .transfers_page import TransfersPage
from .technicians_page import TechniciansPage
from .reports_page import ReportsPage
from .config_page import ConfigPage
